name: Caçador de Vagas Diario

on:
  schedule:
    # 12:00 UTC equivale a 09:00 BRT (Horário de Brasília)
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  rodar-bot:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Força a versão nova e cala o aviso
    permissions:
      contents: write

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v4

    - name: Configurar o Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Executar a varredura
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: bundle exec ruby scraper.rb

    - name: Salvar vagas já processadas no GitHub
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add vagas_vistas.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "chore: atualiza memoria de vagas processadas [skip ci]" && git push)
